### ISSUE TITLE
New email format from Niantic

### ISSUE THREAD

**Issue by sciolto** [healsdata/ingress-portal-tracker#1]
Hi, Niantic has a new Email format for Portal Reviews. Can you fix the script?

Here's an example of portal reject:

Subject: Portal review complete: <Portal Name>
Body: 

```
We've reviewed your Portal submission and given the information you've provided in your submission, we have decided not to accept this candidate.

At this time, we’re not able to provide specific rejection reasons for each submission we review; however, the following are common reasons for rejection:

The candidate is on our PLEASE DON'T SUBMIT list
We couldn't find evidence that the candidate meets any of our ACCEPTANCE CRITERIA
The candidate was submitted in an incorrect location, and we weren't able to find the right location
-NianticOps

<Portal Name>
<Portal Address>
```

**Comment by healsdata** [comment]
So it looks like the subject is the same for rejections, duplicates, and acceptance now? I was previously searching for emails based on subject. This might mean that has to change to search the whole email now.

**Comment by sciolto** [comment]
Yes exaclty, that's no good, is it? I don't know how the first submission confirmation email looks like. Maybe we have to parse the body for those mail as well. I can help if you want. I will try submitting one more portal and wait till they hopefully accept one of my queue (I have many due soon)

**Comment by sciolto** [comment]
Hi, 
 I got a portal accepted today. It's the same format as the reject mails. Just the mail body changes:

Subject:

```
Portal review complete: <Portal Name>
```

Body:

```
Good work, Agent: we've accepted your submission, and this Portal is now available on your Scanner and on the Intel Map. You have been awarded 1000 AP as well as this Portal's Key for your discovery.

-NianticOps
<Portal Name>
<Portal Address>
<Portal Pic>
```

**Comment by healsdata** [comment]
Great, thank you for that. I'll take a look tonight to see if the GMail search will let us look in the body as well. Hopefully it won't be a huge pain.

**Comment by sciolto** [comment]
Looks like there is a similar function 
https://developers.google.com/apps-script/reference/gmail/gmail-message#getBody()

should be easy to parse the content with a regex like:

```
var regExp = new RegExp("/Good work, Agent.*/","g")
```

cheers

**Comment by sciolto** [comment]
Sorry for the spam, but I got a duplicate as well. Here the new mail format for those:

Subject:

```
Portal review complete:<Portal Name>
```

Body:

```
We've reviewed your Portal submission, but we're not able to bring this candidate online at this time.

Your candidate is a duplicate of either an existing Portal or one that's too close to another live Portal to be safely Hacked.

-NianticOps
<Portal Name>
<Portal Address>
<Portal Pic>
```

**Comment by sciolto** [comment]
Still me. I have also the mail format for new submissions:
Subject:

```
Portal submission confirmation:<Portal Name>
```

Body:

```
Thanks for sending your Ingress Portal suggestion for review; this message confirms that we've successfully received your submission.

We review Portal candidates to ensure they meet our Candidate Portal criteria; the review time varies and can take anywhere from a few weeks up to several months. Keep in mind that as long as you've received this email, your candidate was successfully submitted.

-NianticOps
<Portal Name>
<Portal Pic>
```

**Comment by healsdata** [comment]
Thanks for all your help with this! Sad to see the Niantic is taking portal submissions away, but this should cover both the old and new email format.

**Comment by sciolto** [comment]
It works as expected. Good job. Niantic put a stop to submissions by taking temporarely the badge away, but they should put it up again in the future..

**Comment by sciolto** [comment]
Hi, I think new format duplicates are not recognized; they are marked as rejected in the sheet.

Thanks
